# services:
#     nginx:
#         build:
#             context: ./docker/local/nginx
#         environment:
#             TZ: Asia/Tokyo
#         ports:
#             - "80:80"
#         tty: true
#         depends_on:
#             - "go"

#     go:
#         build:
#             context: ./docker/local/go
#         environment:
#             TZ: Asia/Tokyo
#         ports:
#             - 8080:8080
#         volumes:
#             - ./api/:/go/src

#     # mysql:
#     #     build: ./docker/local/mysql
#     #     environment:
#     #         TZ: Asia/Tokyo
#     #         MYSQL_ROOT_PASSWORD: root
#     #         MYSQL_DATABASE: local
#     #     ports:
#     #         - 13306:3306
#     #     volumes:
#     #         - mysql_volume:/var/lib/mysql

# # volumes:
# #     mysql_volume:

services:
    go:
        build:
            context: ./api
        container_name: go
        volumes:
            - ./api/src:/go/src
        environment:
            MYSQL_DATABASE: local
            MYSQL_HOST: mysql
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql
        networks:
            - backend
    nginx:
        image: nginx:1.25.0
        container_name: nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - go
        networks:
            - backend
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_DATABASE: local
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - backend
        ports:
            - "3306:3306"

networks:
    backend:
volumes:
    db_data: